name: Create Release

on:
  workflow_dispatch: # allow manual run
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      release--tag_name: ${{ steps.release.outputs.tag_name }}
      release--releases_created: ${{ steps.release.outputs.releases_created }}
      release--prs_createde: ${{ steps.release.outputs.prs_created }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Starting log
        run: |
          echo "🐧 This job is running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "📰 This job is triggered by this event: ${{ github.event_name }}"

      - name: Check working directory
        run: pwd && ls -la

      - name: Check config file
        run: cat ${{ github.workspace }}/Repo/release-please-config.json || echo "'release-please-config.json' not found"

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          # optional. customize path to release-please-config.json
          config-file: ${{ github.workspace }}/Repo/release-please-config.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: ${{ github.workspace }}/Repo/release-please-manifest.json

      - name: Print release outputs for debugging
        run: |
          echo "Release outputs:"
          echo "RELEASE CREATED: ${{ steps.release.outputs.releases_created }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "PR CREATED/UPDATED: ${{ steps.release.outputs.prs_created }}" | tee -a $GITHUB_STEP_SUMMARY

      - name: Status
        run: echo "🍏 This job's status is ${{ job.status }}."

  release-zip:
    if: ${{ needs.release-please.outputs.release--releases_created == 'true' }}
    runs-on: ubuntu-latest
    needs: release-please

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Starting log
        run: |
          echo "🐧 This job is running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "📰 This job is triggered by this event: ${{ github.event_name }}"

      - name: Print release outputs for debugging
        run: |
          echo "Release outputs:"
          echo "${{ toJson(needs.release-please.outputs.release) }}"

      - name: Create ZIP archive
        run: |
          zip -r release.zip *.ps1 *.rmskin 2>/dev/null || true

      - name: Upload ZIP to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.release--tag_name }} ./release.zip --clobber
          mv release.zip LivelyWallpaperRandom-${{ needs.release-please.outputs.release--tag_name }}.zip
          gh release upload ${{ needs.release-please.outputs.release--tag_name }} ./LivelyWallpaperRandom-${{ needs.release-please.outputs.release--tag_name }}.zip --clobber

      - name: Status
        run: echo "🍏 This job's status is ${{ job.status }}."
